[tasks.up]
description = "Start elasticseaerch"
script = [
    "docker-compose up -d"
]

[tasks.down]
description = "Stop elasticseaerch"
script = [
    "docker-compose down"
]

[tasks.example]
descript = "Run example"
command = "cargo"
args = [
    "run",
    "--example", "${@}"
]